
spring.datasource.url=jdbc:mysql://172.17.0.3:3306/signalement?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------
# CONFIGURATION JPA / HIBERNATE
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=DEBUG

# Activer multipart
spring.servlet.multipart.enabled=true

# Taille max d’un fichier uploadé
spring.servlet.multipart.max-file-size=2MB

# Taille max totale de la requête (utile si plusieurs fichiers)
spring.servlet.multipart.max-request-size=2MB



# pour l envoi de mails de verification
# pour l'envoi de mails de verification (Mailtrap pour tests)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=12f6bdfd9062f6
spring.mail.password=a3c102cd67a0d3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




# Dossier racine pour les fichiers uploadés
# Dossier racine pour les fichiers uploadés
app.upload.dir=uploads/signalements


