# ------------------------------
# CONFIGURATION BASE DE DONNÉES
# ------------------------------
spring.datasource.url=jdbc:mysql://root:jMezEGEtuwkedoaWqkMrVFYKhOCdihWV@mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=jMezEGEtuwkedoaWqkMrVFYKhOCdihWV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------
# CONFIGURATION JPA / HIBERNATE
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=DEBUG

# ------------------------------
# UPLOAD FICHIERS
# ------------------------------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
app.upload.dir=uploads/signalements

# ------------------------------
# ENVOI DE MAILS (Brevo)
# ------------------------------
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=kisitolecosto@gmail.com
spring.mail.password=xsmtpsib-8d1f290f3107e2babf68dda38dc7254368a2ee927935261f31ae473ccf5a105e-YxtHwwlseINsITv6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true